spring:
  main:
    web-application-type: none
    banner-mode: off
  application:
    name: mcp-test
  ai:
    mcp:
      server:
        name: gmod-mcp
        version: 1.0.0
logging:
  pattern:
    console: